services:
  - type: web
    name: flight-price-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon  # or the region closest to your users

